apiVersion: v2
name: unikorn-core
description: A Helm chart for deploying Unikorn Core

type: application

version: v0.1.1
appVersion: v0.1.1

icon: https://raw.githubusercontent.com/eschercloudai/unikorn/main/icons/default.png
