apiVersion: v2
name: unikorn-core
description: A Helm chart for deploying Unikorn Core

type: application

version: 0.1.0
appVersion: 0.1.0

icon: https://raw.githubusercontent.com/eschercloudai/unikorn/main/icons/default.png
